const generateResponse = async (prompt) => {
  console.log("got into generateResponse function... ")
  const openRouterAPI = process.env.OPENROUTER_API;
  const OPENROUTER_MODEL = process.env.OPENROUTER_MODEL;
  const OPENROUTER_URL = process.env.OPENROUTER_URL;
  const res = await fetch(OPENROUTER_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${openRouterAPI}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      models: [
        "deepseek/deepseek-chat-v3-0324",
        "cohere/north-mini-code:free",
        "nvidia/nemotron-3-ultra-550b-a55b:free",
      ],
      messages: [
       
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.2,
    }),
  });

  if (!res.ok) {
    const error = await res.text();
    throw new Error("Open Router Error: " + error);
  }

  const data = await res.json();
  console.log("Result Generated By: "+ data.model);
  return data;
};

module.exports = generateResponse;


